In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


In [2]:
from sklearn.datasets import  load_breast_cancer
from sklearn import linear_model
from sklearn.model_selection import KFold

In [3]:
ss = KFold(n_splits=10, shuffle=True)

In [4]:
data = load_breast_cancer()

X = data.data
y = data.target


In [5]:
clf = linear_model.LogisticRegression()

In [6]:
for train_index,test_index in ss.split(X, y):
    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    clf.fit(X_train, y_train)
    print(clf.score(X_test, y_test))


/home/ma/.bin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ma/.bin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-re

0.9298245614035088
0.9649122807017544
0.8947368421052632
0.9298245614035088
0.9298245614035088
0.9473684210526315
0.9122807017543859
0.9473684210526315
0.9824561403508771
0.9821428571428571


/home/ma/.bin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ma/.bin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-re

In [7]:
np.unique(y, return_counts=True)


(array([0, 1]), array([212, 357]))

In [8]:
(np.unique(y, return_counts=True)[1]/y.size)

array([0.37258348, 0.62741652])

In [9]:
ss = KFold(n_splits=10, shuffle=True)

for train_index, test_index in ss.split(X, y):

    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    print(np.unique(y_train, return_counts=True)[1]/y_train.size,y_train.size,
          np.unique(y_test, return_counts=True)[1]/ y_test.size, y_test.size)
    


[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.375 0.625] 512 [0.35087719 0.64912281] 57
[0.37109375 0.62890625] 512 [0.38596491 0.61403509] 57
[0.38085938 0.61914062] 512 [0.29824561 0.70175439] 57
[0.37109375 0.62890625] 512 [0.38596491 0.61403509] 57
[0.3828125 0.6171875] 512 [0.28070175 0.71929825] 57
[0.36523438 0.63476562] 512 [0.43859649 0.56140351] 57
[0.37109375 0.62890625] 512 [0.38596491 0.61403509] 57
[0.3671875 0.6328125] 512 [0.42105263 0.57894737] 57
[0.36842105 0.63157895] 513 [0.41071429 0.58928571] 56


In [10]:
from sklearn.model_selection import StratifiedKFold
ss = StratifiedKFold(n_splits=10, shuffle=True)

for train_index, test_index in ss.split(X, y):

    X_train, X_test = X[train_index], X[test_index]
    y_train, y_test = y[train_index], y[test_index]

    print(np.unique(y_train, return_counts=True)[1]/y_train.size,y_train.size,
          np.unique(y_test, return_counts=True)[1]/ y_test.size, y_test.size)
    


[0.37109375 0.62890625] 512 [0.38596491 0.61403509] 57
[0.37109375 0.62890625] 512 [0.38596491 0.61403509] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37304688 0.62695312] 512 [0.36842105 0.63157895] 57
[0.37231969 0.62768031] 513 [0.375 0.625] 56


In [11]:

from sklearn.model_selection import cross_val_score

ave_score = cross_val_score(clf, X, y, cv=10)


/home/ma/.bin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/ma/.bin/anaconda3/lib/python3.8/site-packages/sklearn/linear_model/_logistic.py:762: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-re

In [12]:
ave_score

array([0.92982456, 0.92982456, 0.92982456, 0.92982456, 0.94736842,
       0.96491228, 0.92982456, 0.94736842, 0.92982456, 0.96428571])