In [1]:
import numpy as np

import matplotlib.pyplot as plt


plt.set_cmap(plt.cm.gist_ncar)


<Figure size 432x288 with 0 Axes>

In [2]:

def plotBoundary(X, clf, mesh=True, cmap=plt.get_cmap()):
    x_min = min(X[:, 0])
    x_max = max(X[:, 0])
    y_min = min(X[:, 1])
    y_max = max(X[:, 1])

    XX, YY = np.mgrid[x_min:x_max:200j, y_min:y_max:200j]

    z = clf.predict(np.c_[XX.ravel(), YY.ravel()])
    z = z.reshape(XX.shape)

    if mesh:
        plt.pcolormesh(XX, YY, z, zorder=-10, cmap=cmap)
    plt.xlim(x_min, x_max)
    plt.ylim(y_min, y_max)


In [6]:
np.mgrid[1:10:200j, 1:10:200j]

array([[[ 1.        ,  1.        ,  1.        , ...,  1.        ,
          1.        ,  1.        ],
        [ 1.04522613,  1.04522613,  1.04522613, ...,  1.04522613,
          1.04522613,  1.04522613],
        [ 1.09045226,  1.09045226,  1.09045226, ...,  1.09045226,
          1.09045226,  1.09045226],
        ...,
        [ 9.90954774,  9.90954774,  9.90954774, ...,  9.90954774,
          9.90954774,  9.90954774],
        [ 9.95477387,  9.95477387,  9.95477387, ...,  9.95477387,
          9.95477387,  9.95477387],
        [10.        , 10.        , 10.        , ..., 10.        ,
         10.        , 10.        ]],

       [[ 1.        ,  1.04522613,  1.09045226, ...,  9.90954774,
          9.95477387, 10.        ],
        [ 1.        ,  1.04522613,  1.09045226, ...,  9.90954774,
          9.95477387, 10.        ],
        [ 1.        ,  1.04522613,  1.09045226, ...,  9.90954774,
          9.95477387, 10.        ],
        ...,
        [ 1.        ,  1.04522613,  1.09045226, ...,  

In [8]:
np.r_[-1:1:5j]

array([-1. , -0.5,  0. ,  0.5,  1. ])

In [10]:
np.mgrid[1:10, 1:10]

array([[[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [2, 2, 2, 2, 2, 2, 2, 2, 2],
        [3, 3, 3, 3, 3, 3, 3, 3, 3],
        [4, 4, 4, 4, 4, 4, 4, 4, 4],
        [5, 5, 5, 5, 5, 5, 5, 5, 5],
        [6, 6, 6, 6, 6, 6, 6, 6, 6],
        [7, 7, 7, 7, 7, 7, 7, 7, 7],
        [8, 8, 8, 8, 8, 8, 8, 8, 8],
        [9, 9, 9, 9, 9, 9, 9, 9, 9]],

       [[1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9],
        [1, 2, 3, 4, 5, 6, 7, 8, 9]]])